version: "3.8"
services:
  app:
    image: dbdemo:test
    container_name: myapp
    environment:
      DB_URL: jdbc:mysql://db:3307/test
      DB_USER: appuser
      DB_PASSWORD: app123
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true

  db:
    image: mysql:8.0.45-debian
    container_name: mydb
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: test
      MYSQL_USER: appuser
      MYSQL_PASSWORD: app123
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:                        # ← db 블록 안에 있어야 함
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p1111 --silent" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s